def build(bld):
    bld.recurse('libsast')
    bld.recurse('libatm')
    bld.program(
        source   = 'main.cpp',
        target   = bld.path.get_bld().make_node('atm'),
        includes = '.',
        use      = 'libsast libatm BOOST BOOST_TIMER')
